### ISSUE TITLE
Vue fail to mount render function

### ISSUE THREAD

**Issue by avrelaun** [FranckFreiburger/vue-resize-sensor#4]
Using vue-pdf on a webpack 3 project, the render function on resize sensor fails to mount with vue (runtime only).

It seems that using es imports instead of requires on both vue-pdf & vue-resize-sensor fix the problem.

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <ResizeSensor>
       <Vuepdf> at node_modules/vue-pdf/src/pdf.vue
```

**Comment by avrelaun** [comment]
Actually it doesn't fix the problem.
I also tried running the full build with the compiler, same problem.
This is weird because a render function is defined on vue-resize-sensor component...

**Comment by FranckFreiburger** [comment]
I will create a vue-resize-sensor@2 version that will use only esm.

**Comment by jdemoort** [comment]
Any expectation on when the vue-resize-sensor@2 version will become available?
Tx

**Comment by FranckFreiburger** [comment]
very soon...

**Comment by jdemoort** [comment]
Much appreciated!

**Comment by FranckFreiburger** [comment]
please check v2.0.0
(note that vue-pdf has not been updated accordingly)

**Comment by FranckFreiburger** [comment]
please reopen if the problem persists
